// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Root implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CascaderJSON("CascaderJSON"),
		Response("Response"),
		Root_City("MyFirstModule.Root_City");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject)
	{
		if (rootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, rootMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.rootMendixObject = rootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Root(context, mendixObject);
	}

	public static myfirstmodule.proxies.Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Root.initialize(context, mendixObject);
	}

	/**
	 * @return value of CascaderJSON
	 */
	public final java.lang.String getCascaderJSON()
	{
		return getCascaderJSON(getContext());
	}

	/**
	 * @param context
	 * @return value of CascaderJSON
	 */
	public final java.lang.String getCascaderJSON(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CascaderJSON.toString());
	}

	/**
	 * Set value of CascaderJSON
	 * @param cascaderjson
	 */
	public final void setCascaderJSON(java.lang.String cascaderjson)
	{
		setCascaderJSON(getContext(), cascaderjson);
	}

	/**
	 * Set value of CascaderJSON
	 * @param context
	 * @param cascaderjson
	 */
	public final void setCascaderJSON(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cascaderjson)
	{
		getMendixObject().setValue(context, MemberNames.CascaderJSON.toString(), cascaderjson);
	}

	/**
	 * @return value of Response
	 */
	public final java.lang.String getResponse()
	{
		return getResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of Response
	 */
	public final java.lang.String getResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Response.toString());
	}

	/**
	 * Set value of Response
	 * @param response
	 */
	public final void setResponse(java.lang.String response)
	{
		setResponse(getContext(), response);
	}

	/**
	 * Set value of Response
	 * @param context
	 * @param response
	 */
	public final void setResponse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String response)
	{
		getMendixObject().setValue(context, MemberNames.Response.toString(), response);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Root_City
	 */
	public final myfirstmodule.proxies.City getRoot_City() throws com.mendix.core.CoreException
	{
		return getRoot_City(getContext());
	}

	/**
	 * @param context
	 * @return value of Root_City
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.City getRoot_City(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.City result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Root_City.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.City.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Root_City
	 * @param root_city
	 */
	public final void setRoot_City(myfirstmodule.proxies.City root_city)
	{
		setRoot_City(getContext(), root_city);
	}

	/**
	 * Set value of Root_City
	 * @param context
	 * @param root_city
	 */
	public final void setRoot_City(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.City root_city)
	{
		if (root_city == null) {
			getMendixObject().setValue(context, MemberNames.Root_City.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Root_City.toString(), root_city.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rootMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Root that = (myfirstmodule.proxies.Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
