// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_InitializeDataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_InitializeData");
		return builder;
	}

	public static void aCT_InitializeData(IContext context)
	{
		aCT_InitializeDataBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Root_ResetJSONBuilder(
		myfirstmodule.proxies.Root _root
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_Root_ResetJSON");
		builder = builder.withParam("Root", _root);
		return builder;
	}

	public static void aCT_Root_ResetJSON(
		IContext context,
		myfirstmodule.proxies.Root _root
	)
	{
		aCT_Root_ResetJSONBuilder(
				_root
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Root_Cascader2LayerBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.DS_Root_Cascader2Layer");
		return builder;
	}

	public static myfirstmodule.proxies.Root dS_Root_Cascader2Layer(IContext context)
	{
		Object result = dS_Root_Cascader2LayerBuilder().execute(context);
		return result == null ? null : myfirstmodule.proxies.Root.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Root_Cascader3LayerBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.DS_Root_Cascader3Layer");
		return builder;
	}

	public static myfirstmodule.proxies.Root dS_Root_Cascader3Layer(IContext context)
	{
		Object result = dS_Root_Cascader3LayerBuilder().execute(context);
		return result == null ? null : myfirstmodule.proxies.Root.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Root_Cascader4LayerBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.DS_Root_Cascader4Layer");
		return builder;
	}

	public static myfirstmodule.proxies.Root dS_Root_Cascader4Layer(IContext context)
	{
		Object result = dS_Root_Cascader4LayerBuilder().execute(context);
		return result == null ? null : myfirstmodule.proxies.Root.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Root_CascaderDisabledOptionsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.DS_Root_CascaderDisabledOptions");
		return builder;
	}

	public static myfirstmodule.proxies.Root dS_Root_CascaderDisabledOptions(IContext context)
	{
		Object result = dS_Root_CascaderDisabledOptionsBuilder().execute(context);
		return result == null ? null : myfirstmodule.proxies.Root.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCH_Root_CascaderBuilder(
		myfirstmodule.proxies.Root _root
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.OCH_Root_Cascader");
		builder = builder.withParam("Root", _root);
		return builder;
	}

	public static void oCH_Root_Cascader(
		IContext context,
		myfirstmodule.proxies.Root _root
	)
	{
		oCH_Root_CascaderBuilder(
				_root
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_DeleteAllDataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.SUB_DeleteAllData");
		return builder;
	}

	public static void sUB_DeleteAllData(IContext context)
	{
		sUB_DeleteAllDataBuilder().execute(context);
	}
}
